version: '3.0'
services:
  postgres:
    image: postgres
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=GameInventory
    ports:
        - 5433:5432

  gameinventory:
    image: gameinventory
    build:
      context: .
      dockerfile: GameInventory/Dockerfile
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    links:
        - postgres
    ports:
        - 5200:5200

networks:
  mynetwork:
     driver: bridge