version: '3.0'
services:
  postgres:
    image: postgres
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=GameInventory
    ports:
        - 5433:5432

  gameinventory:
    image: gameinventory
    build:
      context: .
      dockerfile: GameInventory/Dockerfile
    depends_on:
      - postgres
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://postgres:5432/camunda
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
      - ADMIN_LOGIN=admin
      - ADMIN_PASSWORD=admin
      - WAIT_FOR=postgres:5432
    links:
        - postgres
    ports:
        - 5200:5200
